In [26]:
import pandas as pd

# Acessando arquivos

In [27]:
viagens_validas = pd.read_excel('/Users/guilistocco/Documents/TCC 2 - Ônibus/BancoDados/Dados brutos/matriz_junho_mapeada.xlsx', index_col='Unnamed: 0')
viagens_validas.columns = ['index_col', 'day', 'device_id', 'periodo', 'dataInicio', 'dataFim',
       'sequence', 'distance(m)', 'duration(s)', 'latitudeI', 'longitudeI',
       'latitudeF', 'longitudeF', 'Nome_PontoI', 'Nome_PontoF', 'PontoFinal',
       'dist_PontoF', 'PontoInicial', 'dist_PontoI']

viagens_validas = viagens_validas[[  'index_col', 'day', 'device_id', 'periodo', 'dataInicio', 'dataFim',
       'sequence', 'distance(m)', 'duration(s)', 'PontoInicial','Nome_PontoI','latitudeI', 'longitudeI','dist_PontoI',
       'PontoFinal','Nome_PontoF','latitudeF', 'longitudeF',  'dist_PontoF'  ]]
viagens_validas['PontoInicial']    = viagens_validas['PontoInicial']    -1
viagens_validas['PontoFinal']      = viagens_validas['PontoFinal']      -1
viagens_validas

,index_col,day,device_id,periodo,dataInicio,dataFim,sequence,distance(m),duration(s),PontoInicial,Nome_PontoI,latitudeI,longitudeI,dist_PontoI,PontoFinal,Nome_PontoF,latitudeF,longitudeF,dist_PontoF
0,None_6,1,0,Manha,2021-06-01 06:44:02,2021-06-01 06:45:20,1,333.068136,78.0,33,Hemocentro / FCM,-22.827145,-47.061214,0.001096,29,Escola Sérgio P. Porto (PONTO INICIAL),-22.829490,-47.060281,0.000124
1,None_6,1,0,Manha,2021-06-01 07:58:17,2021-06-01 07:59:35,4,362.164440,78.0,34,Hemocentro / FCM,-22.827037,-47.061207,0.001011,29,Escola Sérgio P. Porto (PONTO FINAL),-22.829638,-47.060359,0.000179
2,None_6,1,0,Manha,2021-06-01 09:06:10,2021-06-01 09:07:28,6,350.063969,78.0,33,Hemocentro / FCM,-22.827116,-47.061166,0.000957,29,Escola Sérgio P. Porto (PONTO INICIAL),-22.829648,-47.060414,0.000180
3,None_6,1,0,Manha,2021-06-01 11:10:03,2021-06-01 11:11:21,7,361.522224,78.0,34,Hemocentro / FCM,-22.827030,-47.061240,0.001020,29,Escola Sérgio P. Porto (PONTO FINAL),-22.829614,-47.060350,0.000153
4,None_6,1,0,Manha,2021-06-01 11:57:21,2021-06-01 11:58:42,9,339.187065,81.0,33,Hemocentro / FCM,-22.827211,-47.061172,0.000860,29,Escola Sérgio P. Porto (PONTO INICIAL),-22.829681,-47.060513,0.000156
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14483,None_8,31,92524,Manha,2021-08-31 12:57:57,2021-08-31 12:59:37,1,527.011253,100.0,13,HC (Portaria F1),-22.829433,-47.064937,0.000081,11,CECOM,-22.825647,-47.066167,0.001011
14484,None_8,31,93049,Tarde,2021-08-31 15:31:56,2021-08-31 15:33:16,1,825.952595,80.0,25,CECOM,-22.826262,-47.067667,0.001754,13,Sobrapar,-22.831246,-47.063677,0.001125
14485,None_8,31,93049,Tarde,2021-08-31 15:31:56,2021-08-31 15:33:16,2,825.952595,80.0,25,CECOM,-22.826262,-47.067667,0.001754,13,Sobrapar,-22.831246,-47.063677,0.001125
14486,None_8,31,93166,Tarde,2021-08-31 16:19:17,2021-08-31 16:23:33,1,821.356800,256.0,13,DGA / Praça das Bandeiras,-22.831021,-47.063912,0.000265,10,CECOM,-22.824985,-47.065243,0.001511
14487,None_8,31,93183,Tarde,2021-08-31 16:22:39,2021-08-31 16:23:42,1,388.584395,63.0,25,DGA / Praça das Bandeiras,-22.827279,-47.067400,0.000086,10,Sobrapar,-22.824928,-47.065532,0.000204

In [28]:
clusters = pd.read_excel('/Users/guilistocco/Documents/TCC 2 - Ônibus/BancoDados/Dados brutos/clusters_18medoids.xlsx')
clusters

    clusters  medoids
0          0        5
1          1        1
2          2        5
3          3        5
4          3       30
5          4       23
6          5        5
7          6        7
8          7        7
9          8        8
10         9       14
11        10       10
12        11       10
13        12       15
14        13       13
15        14       14
16        15       15
17        16       32
18        17       17
19        18       18
20        19       23
21        20       20
22        21       21
23        22       30
24        23       23
25        24       32
26        25       17
27        26       26
28        27       17
29        28       28
30        29       33
31        30       30
32        31       28
33        32       32
34        33       33
35        34       33

In [29]:
clusters.medoids.value_counts()

5     4
32    3
17    3
33    3
23    3
30    3
7     2
14    2
10    2
15    2
28    2
8     1
1     1
18    1
20    1
21    1
26    1
13    1
Name: medoids, dtype: int64

# Formacao do dicionario e remapeamento dos pontos de Inicio e Final

In [32]:
dict_ = {}
for dic in range((clusters.shape[0])):
    # print(dic)
    dict_[clusters['clusters'][dic]] = clusters['medoids'][dic]


dict_

{0: 5,
 1: 1,
 2: 5,
 3: 30,
 4: 23,
 5: 5,
 6: 7,
 7: 7,
 8: 8,
 9: 14,
 10: 10,
 11: 10,
 12: 15,
 13: 13,
 14: 14,
 15: 15,
 16: 32,
 17: 17,
 18: 18,
 19: 23,
 20: 20,
 21: 21,
 22: 30,
 23: 23,
 24: 32,
 25: 17,
 26: 26,
 27: 17,
 28: 28,
 29: 33,
 30: 30,
 31: 28,
 32: 32,
 33: 33,
 34: 33}

In [33]:
viagens_validas['NEW_PontoInicial'] = viagens_validas['PontoInicial'].map(dict_)
viagens_validas['NEW_PontoFinal']   = viagens_validas['PontoFinal'].map(dict_)

viagens_validas['NEW_PontoInicial']  = viagens_validas['NEW_PontoInicial'].astype(int) 
viagens_validas['NEW_PontoFinal']    = viagens_validas['NEW_PontoFinal']  .astype(int)

In [35]:
agrupamento = viagens_validas.groupby(['NEW_PontoInicial','NEW_PontoFinal']).agg({'sequence':'count'}).reset_index()

OD = agrupamento.pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)

OD

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,4.0,121.0,95.0,0.0,216.0,32.0,64.0,67.0,200.0,15.0,154.0,25.0,207.0,55.0,52.0,34.0,2.0
5,11.0,118.0,4.0,0.0,28.0,0.0,15.0,26.0,7.0,8.0,6.0,94.0,18.0,120.0,382.0,0.0,8.0
7,29.0,74.0,4.0,0.0,91.0,12.0,106.0,9.0,42.0,8.0,3.0,12.0,6.0,160.0,5.0,42.0,18.0
8,86.0,2.0,9.0,9.0,11.0,7.0,7.0,10.0,17.0,2.0,19.0,0.0,19.0,4.0,13.0,0.0,22.0
10,103.0,98.0,73.0,51.0,33.0,324.0,44.0,15.0,688.0,72.0,17.0,16.0,57.0,94.0,13.0,518.0,325.0
13,47.0,17.0,8.0,17.0,217.0,24.0,8.0,6.0,142.0,2.0,0.0,0.0,1.0,9.0,3.0,88.0,207.0
14,15.0,39.0,58.0,0.0,19.0,7.0,6.0,23.0,13.0,6.0,4.0,13.0,10.0,165.0,20.0,16.0,32.0
15,29.0,30.0,48.0,0.0,34.0,20.0,54.0,8.0,30.0,3.0,6.0,3.0,11.0,66.0,10.0,2.0,12.0
17,61.0,61.0,21.0,25.0,772.0,239.0,11.0,8.0,148.0,22.0,10.0,6.0,35.0,52.0,8.0,213.0,396.0
18,2.0,1.0,0.0,0.0,32.0,5.0,0.0,1.0,9.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,38.0
20,112.0,14.0,14.0,0.0,31.0,0.0,10.0,16.0,23.0,4.0,0.0,8.0,78.0,6.0,7.0,4.0,0.0
21,13.0,1105.0,0.0,0.0,0.0,0.0,4.0,4.0,0.0,0.0,1.0,101.0,2.0,4.0,0.0,0.0,0.0
23,146.0,119.0,26.0,0.0,24.0,0.0,21.0,20.0,28.0,5.0,27.0,3.0,18.0,21.0,25.0,4.0,0.0
28,9.0,32.0,1.0,0.0,41.0,2.0,4.0,16.0,9.0,12.0,7.0,8.0,9.0,1.0,55.0,1.0,16.0
30,1.0,9.0,2.0,2.0,36.0,3.0,3.0,0.0,4.0,24.0,0.0,1.0,2.0,21.0,68.0,1.0,14.0
32,109.0,31.0,91.0,63.0,28.0,9.0,27.0,7.0,37.0,8.0,10.0,8.0,36.0,24.0,8.0,53.0,36.0
33,9.0,15.0,12.0,11.0,167.0,252.0,25.0,7.0,205.0,52.0,0.0,0.0,4.0,34.0,20.0,45.0,1209.0

# OD Horaria

In [45]:
viagens_validas['horario'] = viagens_validas['dataInicio'].dt.hour
viagens_validas

,index_col,day,device_id,periodo,dataInicio,dataFim,sequence,distance(m),duration(s),PontoInicial,...,longitudeI,dist_PontoI,PontoFinal,Nome_PontoF,latitudeF,longitudeF,dist_PontoF,NEW_PontoInicial,NEW_PontoFinal,horario
0,None_6,1,0,Manha,2021-06-01 06:44:02,2021-06-01 06:45:20,1,333.068136,78.0,33,...,-47.061214,0.001096,29,Escola Sérgio P. Porto (PONTO INICIAL),-22.829490,-47.060281,0.000124,33,33,6
1,None_6,1,0,Manha,2021-06-01 07:58:17,2021-06-01 07:59:35,4,362.164440,78.0,34,...,-47.061207,0.001011,29,Escola Sérgio P. Porto (PONTO FINAL),-22.829638,-47.060359,0.000179,33,33,7
2,None_6,1,0,Manha,2021-06-01 09:06:10,2021-06-01 09:07:28,6,350.063969,78.0,33,...,-47.061166,0.000957,29,Escola Sérgio P. Porto (PONTO INICIAL),-22.829648,-47.060414,0.000180,33,33,9
3,None_6,1,0,Manha,2021-06-01 11:10:03,2021-06-01 11:11:21,7,361.522224,78.0,34,...,-47.061240,0.001020,29,Escola Sérgio P. Porto (PONTO FINAL),-22.829614,-47.060350,0.000153,33,33,11
4,None_6,1,0,Manha,2021-06-01 11:57:21,2021-06-01 11:58:42,9,339.187065,81.0,33,...,-47.061172,0.000860,29,Escola Sérgio P. Porto (PONTO INICIAL),-22.829681,-47.060513,0.000156,33,33,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14483,None_8,31,92524,Manha,2021-08-31 12:57:57,2021-08-31 12:59:37,1,527.011253,100.0,13,...,-47.064937,0.000081,11,CECOM,-22.825647,-47.066167,0.001011,13,10,12
14484,None_8,31,93049,Tarde,2021-08-31 15:31:56,2021-08-31 15:33:16,1,825.952595,80.0,25,...,-47.067667,0.001754,13,Sobrapar,-22.831246,-47.063677,0.001125,17,13,15
14485,None_8,31,93049,Tarde,2021-08-31 15:31:56,2021-08-31 15:33:16,2,825.952595,80.0,25,...,-47.067667,0.001754,13,Sobrapar,-22.831246,-47.063677,0.001125,17,13,15
14486,None_8,31,93166,Tarde,2021-08-31 16:19:17,2021-08-31 16:23:33,1,821.356800,256.0,13,...,-47.063912,0.000265,10,CECOM,-22.824985,-47.065243,0.001511,13,10,16
14487,None_8,31,93183,Tarde,2021-08-31 16:22:39,2021-08-31 16:23:42,1,388.584395,63.0,25,...,-47.067400,0.000086,10,Sobrapar,-22.824928,-47.065532,0.000204,17,10,16

In [ ]:
viagens_validas.horario.value_counts().sort_index()

4        1
5        3
6      394
7     1203
8     1167
9      833
10      97
11    1750
12    1796
13    1589
14    1218
15    1498
16    1089
17    1078
18     483
19     289
Name: horario, dtype: int64

In [46]:
agrupamento_horario = viagens_validas.groupby([ 'horario',   'NEW_PontoInicial','NEW_PontoFinal']).agg({'sequence':'count'}).reset_index()
agrupamento_horario

      horario  NEW_PontoInicial  NEW_PontoFinal  sequence
0           4                33              33         1
1           5                33              33         3
2           6                 1               1         2
3           6                 1               5         2
4           6                 1              18         1
...       ...               ...             ...       ...
1936       19                32               7         4
1937       19                32              23         1
1938       19                33              10         2
1939       19                33              13         4
1940       19                33              33         4

[1941 rows x 4 columns]

In [47]:
agrupamento_horario.loc[agrupamento_horario['horario'] == 6]

    horario  NEW_PontoInicial  NEW_PontoFinal  sequence
2         6                 1               1         2
3         6                 1               5         2
4         6                 1              18         1
5         6                 1              20         1
6         6                 1              23         6
..      ...               ...             ...       ...
82        6                33              10         1
83        6                33              13        17
84        6                33              17         4
85        6                33              18         2
86        6                33              33        86

[85 rows x 4 columns]

In [51]:
hora6 = agrupamento_horario.loc[agrupamento_horario['horario'] == 6].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora6

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,
1,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,6.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
8,7.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0
10,1.0,11.0,0.0,5.0,0.0,2.0,1.0,0.0,16.0,7.0,1.0,2.0,0.0,0.0,11.0,6.0
13,0.0,1.0,0.0,0.0,10.0,1.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,1.0,3.0,15.0
14,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,4.0,0.0,1.0,0.0
15,1.0,0.0,2.0,0.0,0.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0
17,2.0,4.0,0.0,1.0,32.0,10.0,0.0,1.0,5.0,1.0,0.0,2.0,2.0,2.0,7.0,12.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
20,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
23,0.0,4.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
28,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
30,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,8.0,0.0,2.0,3.0,1.0,1.0,0.0,0.0,3.0,2.0,1.0,6.0,2.0,1.0,3.0,5.0
33,0.0,0.0,0.0,0.0,1.0,17.0,0.0,0.0,4.0,2.0,0.0,0.0,0.0,0.0,0.0,86.0

In [54]:
hora4 = agrupamento_horario.loc[agrupamento_horario['horario'] == 4].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora5 = agrupamento_horario.loc[agrupamento_horario['horario'] == 5].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora6 = agrupamento_horario.loc[agrupamento_horario['horario'] == 6].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora7 = agrupamento_horario.loc[agrupamento_horario['horario'] == 7].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora8 = agrupamento_horario.loc[agrupamento_horario['horario'] == 8].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora9 = agrupamento_horario.loc[agrupamento_horario['horario'] == 9].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora10 = agrupamento_horario.loc[agrupamento_horario['horario'] == 10].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora11 = agrupamento_horario.loc[agrupamento_horario['horario'] == 11].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora12 = agrupamento_horario.loc[agrupamento_horario['horario'] == 12].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora13 = agrupamento_horario.loc[agrupamento_horario['horario'] == 13].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora14 = agrupamento_horario.loc[agrupamento_horario['horario'] == 14].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora15 = agrupamento_horario.loc[agrupamento_horario['horario'] == 15].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora16 = agrupamento_horario.loc[agrupamento_horario['horario'] == 16].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora17 = agrupamento_horario.loc[agrupamento_horario['horario'] == 17].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora18 = agrupamento_horario.loc[agrupamento_horario['horario'] == 18].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)
hora19 = agrupamento_horario.loc[agrupamento_horario['horario'] == 19].pivot(index= 'NEW_PontoInicial', columns='NEW_PontoFinal', values='sequence').fillna(0)

In [53]:
hora17

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,0.0,0.0,10.0,0.0,14.0,2.0,7.0,16.0,13.0,0.0,17.0,1.0,11.0,8.0,1.0,6.0,0.0
5,2.0,6.0,0.0,0.0,1.0,0.0,0.0,6.0,0.0,0.0,2.0,14.0,3.0,5.0,23.0,0.0,0.0
7,9.0,2.0,1.0,0.0,4.0,4.0,15.0,1.0,8.0,1.0,2.0,1.0,2.0,13.0,0.0,6.0,5.0
8,3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
10,6.0,3.0,5.0,5.0,6.0,31.0,1.0,0.0,42.0,4.0,2.0,2.0,2.0,1.0,1.0,55.0,37.0
13,5.0,0.0,0.0,0.0,11.0,1.0,0.0,1.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,8.0
14,2.0,1.0,8.0,0.0,2.0,1.0,0.0,5.0,1.0,0.0,0.0,1.0,0.0,4.0,0.0,3.0,1.0
15,3.0,3.0,3.0,0.0,1.0,2.0,2.0,0.0,9.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,2.0
17,4.0,1.0,0.0,2.0,33.0,24.0,0.0,0.0,9.0,3.0,2.0,1.0,1.0,2.0,0.0,15.0,31.0
18,0.0,0.0,0.0,0.0,6.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
20,10.0,3.0,1.0,0.0,2.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
21,2.0,111.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,13.0,0.0,0.0,0.0,0.0,0.0
23,13.0,4.0,3.0,0.0,0.0,0.0,1.0,3.0,2.0,0.0,3.0,1.0,2.0,0.0,0.0,1.0,0.0
28,1.0,1.0,0.0,0.0,6.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4.0,0.0,1.0
30,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0
32,2.0,4.0,4.0,5.0,2.0,0.0,2.0,1.0,2.0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0
33,2.0,1.0,1.0,2.0,16.0,16.0,0.0,0.0,29.0,8.0,0.0,0.0,0.0,0.0,0.0,8.0,74.0

In [56]:
# writer = pd.ExcelWriter('Output de dados/OD_horarias.xlsx', engine='xlsxwriter')

# # Write each dataframe to a different worksheet.
# hora4.to_excel(writer, sheet_name='hora4')      ## nao tem 18 pontos
# hora5.to_excel(writer, sheet_name='hora5')      ## nao tem 18 pontos
# hora6.to_excel(writer, sheet_name='hora6')      ## nao tem 18 pontos
# hora7.to_excel(writer, sheet_name='hora7')
# hora8.to_excel(writer, sheet_name='hora8')
# hora9.to_excel(writer, sheet_name='hora9')      ## nao tem 18 pontos
# hora10.to_excel(writer, sheet_name='hora10')    ## nao tem 18 pontos
# hora11.to_excel(writer, sheet_name='hora11')
# hora12.to_excel(writer, sheet_name='hora12')
# hora13.to_excel(writer, sheet_name='hora13')
# hora14.to_excel(writer, sheet_name='hora14')
# hora15.to_excel(writer, sheet_name='hora15')
# hora16.to_excel(writer, sheet_name='hora16')
# hora17.to_excel(writer, sheet_name='hora17')
# hora18.to_excel(writer, sheet_name='hora18')    ## nao tem 18 pontos
# hora19.to_excel(writer, sheet_name='hora19')    ## nao tem 18 pontos

# # Close the Pandas Excel writer and output the Excel file.
# writer.save()

In [57]:
hora6 +hora7 +hora8

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,3.0,13.0,14.0,0.0,20.0,3.0,8.0,7.0,22.0,2.0,45.0,NaN,25.0,9.0,9.0,5.0,0.0
5,4.0,21.0,2.0,0.0,2.0,0.0,1.0,4.0,0.0,1.0,1.0,NaN,5.0,15.0,83.0,0.0,1.0
7,1.0,17.0,0.0,0.0,10.0,1.0,17.0,2.0,3.0,1.0,0.0,NaN,0.0,33.0,1.0,8.0,3.0
8,18.0,1.0,4.0,2.0,4.0,2.0,2.0,0.0,2.0,0.0,4.0,NaN,8.0,1.0,8.0,0.0,7.0
10,9.0,27.0,12.0,11.0,1.0,46.0,11.0,1.0,135.0,14.0,4.0,NaN,12.0,7.0,2.0,71.0,43.0
13,6.0,4.0,6.0,0.0,38.0,7.0,1.0,0.0,31.0,0.0,0.0,NaN,0.0,1.0,2.0,15.0,57.0
14,2.0,6.0,9.0,0.0,3.0,0.0,0.0,2.0,1.0,1.0,0.0,NaN,0.0,27.0,2.0,8.0,5.0
15,3.0,6.0,8.0,0.0,0.0,1.0,16.0,4.0,2.0,0.0,2.0,NaN,1.0,5.0,2.0,0.0,3.0
17,11.0,17.0,6.0,4.0,171.0,47.0,4.0,2.0,32.0,4.0,1.0,NaN,4.0,8.0,4.0,40.0,85.0
18,2.0,0.0,0.0,0.0,6.0,2.0,0.0,1.0,0.0,2.0,0.0,NaN,0.0,0.0,0.0,0.0,20.0
20,11.0,2.0,1.0,0.0,4.0,0.0,1.0,2.0,0.0,1.0,0.0,NaN,17.0,3.0,1.0,0.0,0.0
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,22.0,32.0,5.0,0.0,1.0,0.0,6.0,6.0,6.0,0.0,0.0,NaN,2.0,6.0,4.0,0.0,0.0
28,2.0,12.0,1.0,0.0,2.0,1.0,1.0,3.0,6.0,2.0,0.0,NaN,3.0,0.0,14.0,1.0,3.0
30,0.0,8.0,1.0,2.0,0.0,1.0,0.0,0.0,1.0,6.0,0.0,NaN,1.0,1.0,23.0,1.0,5.0
32,25.0,12.0,19.0,8.0,7.0,3.0,12.0,0.0,12.0,3.0,2.0,NaN,16.0,8.0,3.0,14.0,10.0
33,2.0,3.0,2.0,2.0,20.0,74.0,2.0,1.0,39.0,7.0,0.0,NaN,4.0,5.0,2.0,7.0,286.0

In [58]:
hora7 +hora8 +hora9

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,2.0,19.0,23.0,0.0,43.0,6.0,15.0,11.0,51.0,3.0,51.0,4.0,32.0,13.0,9.0,7.0,0.0
5,4.0,30.0,2.0,0.0,2.0,0.0,1.0,6.0,1.0,1.0,1.0,24.0,5.0,16.0,115.0,0.0,1.0
7,2.0,25.0,0.0,0.0,16.0,1.0,23.0,2.0,6.0,3.0,0.0,3.0,0.0,50.0,2.0,9.0,4.0
8,15.0,1.0,4.0,1.0,4.0,3.0,1.0,0.0,2.0,0.0,5.0,0.0,8.0,1.0,9.0,0.0,9.0
10,12.0,23.0,19.0,8.0,3.0,51.0,15.0,2.0,150.0,9.0,4.0,5.0,12.0,10.0,3.0,76.0,46.0
13,7.0,3.0,6.0,1.0,34.0,8.0,1.0,0.0,33.0,0.0,0.0,0.0,0.0,3.0,1.0,19.0,53.0
14,2.0,10.0,12.0,0.0,5.0,0.0,0.0,5.0,4.0,0.0,0.0,2.0,0.0,37.0,3.0,7.0,5.0
15,3.0,8.0,10.0,0.0,2.0,0.0,14.0,4.0,2.0,0.0,2.0,1.0,2.0,5.0,2.0,0.0,1.0
17,9.0,16.0,10.0,4.0,179.0,58.0,6.0,1.0,33.0,3.0,2.0,2.0,2.0,7.0,2.0,41.0,88.0
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,14.0,2.0,3.0,0.0,5.0,0.0,3.0,3.0,2.0,2.0,0.0,1.0,17.0,4.0,1.0,0.0,0.0
21,5.0,296.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,21.0,1.0,0.0,0.0,0.0,0.0
23,30.0,37.0,5.0,0.0,5.0,0.0,9.0,5.0,6.0,0.0,3.0,1.0,1.0,5.0,9.0,0.0,0.0
28,2.0,17.0,1.0,0.0,3.0,1.0,1.0,4.0,7.0,2.0,1.0,2.0,2.0,0.0,17.0,1.0,3.0
30,1.0,5.0,1.0,2.0,1.0,1.0,0.0,0.0,1.0,8.0,0.0,0.0,1.0,1.0,31.0,1.0,5.0
32,25.0,14.0,26.0,12.0,7.0,3.0,13.0,0.0,12.0,1.0,2.0,2.0,11.0,6.0,2.0,16.0,6.0
33,2.0,6.0,2.0,2.0,22.0,72.0,2.0,1.0,42.0,7.0,0.0,0.0,4.0,6.0,2.0,8.0,279.0

In [59]:
hora8 +hora9+hora10

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,1.0,16.0,20.0,0.0,40.0,5.0,14.0,11.0,43.0,2.0,32.0,NaN,32.0,13.0,5.0,6.0,1.0
5,2.0,22.0,2.0,0.0,1.0,0.0,0.0,5.0,1.0,1.0,1.0,NaN,3.0,11.0,79.0,0.0,1.0
7,2.0,21.0,0.0,0.0,10.0,1.0,15.0,0.0,6.0,4.0,0.0,NaN,0.0,43.0,2.0,4.0,3.0
8,15.0,1.0,4.0,1.0,1.0,1.0,1.0,0.0,2.0,0.0,4.0,NaN,6.0,0.0,9.0,0.0,5.0
10,8.0,18.0,13.0,4.0,2.0,27.0,10.0,2.0,75.0,6.0,3.0,NaN,5.0,6.0,3.0,44.0,26.0
13,3.0,2.0,0.0,1.0,21.0,4.0,1.0,0.0,16.0,0.0,0.0,NaN,0.0,3.0,1.0,12.0,24.0
14,0.0,7.0,11.0,0.0,5.0,0.0,0.0,5.0,3.0,0.0,0.0,NaN,0.0,32.0,3.0,4.0,5.0
15,2.0,5.0,8.0,0.0,2.0,0.0,12.0,3.0,3.0,0.0,0.0,NaN,1.0,4.0,2.0,0.0,0.0
17,4.0,6.0,5.0,2.0,104.0,43.0,4.0,0.0,17.0,1.0,1.0,NaN,0.0,5.0,0.0,26.0,54.0
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,16.0,29.0,5.0,0.0,6.0,0.0,9.0,2.0,4.0,1.0,3.0,NaN,1.0,3.0,9.0,0.0,0.0
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,1.0,2.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,6.0,0.0,NaN,0.0,1.0,23.0,0.0,1.0
32,24.0,5.0,20.0,11.0,4.0,2.0,6.0,0.0,6.0,2.0,3.0,NaN,7.0,4.0,2.0,16.0,2.0
33,3.0,5.0,1.0,3.0,9.0,39.0,0.0,1.0,23.0,6.0,0.0,NaN,4.0,4.0,2.0,3.0,178.0

In [60]:
hora9+hora10+hora11

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,1.0,74.0,36.0,0.0,107.0,12.0,33.0,23.0,72.0,3.0,21.0,NaN,51.0,11.0,18.0,8.0,1.0
5,0.0,25.0,0.0,0.0,0.0,0.0,1.0,4.0,1.0,0.0,0.0,NaN,4.0,30.0,74.0,0.0,0.0
7,2.0,18.0,0.0,0.0,21.0,1.0,25.0,0.0,9.0,3.0,1.0,NaN,1.0,37.0,2.0,5.0,2.0
8,13.0,0.0,1.0,1.0,1.0,1.0,2.0,1.0,3.0,0.0,3.0,NaN,4.0,0.0,1.0,0.0,3.0
10,17.0,17.0,16.0,8.0,2.0,25.0,9.0,4.0,82.0,7.0,2.0,NaN,8.0,18.0,5.0,72.0,39.0
13,13.0,8.0,1.0,4.0,28.0,3.0,0.0,2.0,31.0,1.0,0.0,NaN,1.0,5.0,0.0,24.0,35.0
14,0.0,5.0,10.0,0.0,3.0,0.0,1.0,4.0,3.0,0.0,2.0,NaN,1.0,24.0,6.0,3.0,3.0
15,10.0,6.0,10.0,0.0,5.0,2.0,5.0,0.0,8.0,0.0,1.0,NaN,4.0,4.0,1.0,0.0,2.0
17,5.0,21.0,7.0,3.0,107.0,41.0,4.0,0.0,23.0,1.0,1.0,NaN,5.0,15.0,1.0,38.0,70.0
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,34.0,28.0,4.0,0.0,7.0,0.0,5.0,3.0,6.0,2.0,9.0,NaN,0.0,3.0,7.0,1.0,0.0
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,1.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,3.0,0.0,NaN,0.0,1.0,12.0,0.0,1.0
32,23.0,4.0,18.0,14.0,2.0,1.0,3.0,2.0,11.0,2.0,4.0,NaN,4.0,1.0,1.0,13.0,10.0
33,2.0,3.0,1.0,2.0,16.0,37.0,1.0,0.0,28.0,10.0,0.0,NaN,0.0,2.0,2.0,11.0,241.0

In [61]:
hora10+hora11+hora12

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,0.0,83.0,35.0,0.0,100.0,13.0,29.0,22.0,63.0,8.0,26.0,NaN,62.0,14.0,39.0,6.0,2.0
5,1.0,24.0,1.0,0.0,1.0,0.0,2.0,4.0,1.0,1.0,0.0,NaN,4.0,31.0,101.0,0.0,3.0
7,5.0,21.0,0.0,0.0,29.0,2.0,31.0,2.0,10.0,2.0,1.0,NaN,2.0,31.0,2.0,10.0,4.0
8,30.0,1.0,0.0,1.0,2.0,0.0,3.0,8.0,6.0,1.0,6.0,NaN,3.0,2.0,3.0,0.0,2.0
10,49.0,42.0,21.0,15.0,3.0,57.0,15.0,7.0,162.0,10.0,3.0,NaN,20.0,24.0,6.0,147.0,73.0
13,22.0,8.0,1.0,8.0,69.0,3.0,2.0,2.0,42.0,1.0,0.0,NaN,1.0,4.0,0.0,38.0,44.0
14,0.0,12.0,12.0,0.0,5.0,3.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,34.0,11.0,4.0,17.0
15,13.0,8.0,12.0,0.0,7.0,2.0,8.0,1.0,8.0,1.0,1.0,NaN,4.0,6.0,2.0,0.0,4.0
17,18.0,24.0,6.0,4.0,182.0,45.0,2.0,2.0,35.0,1.0,1.0,NaN,10.0,21.0,1.0,70.0,109.0
18,0.0,1.0,0.0,0.0,9.0,0.0,0.0,0.0,4.0,0.0,0.0,NaN,0.0,1.0,0.0,0.0,0.0
20,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,33.0,28.0,5.0,0.0,8.0,0.0,5.0,7.0,6.0,2.0,7.0,NaN,1.0,6.0,7.0,1.0,0.0
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,0.0,0.0,0.0,0.0,2.0,1.0,1.0,0.0,1.0,2.0,0.0,NaN,0.0,3.0,9.0,0.0,3.0
32,31.0,4.0,21.0,19.0,9.0,1.0,4.0,4.0,14.0,3.0,5.0,NaN,6.0,2.0,3.0,19.0,12.0
33,4.0,2.0,1.0,4.0,54.0,54.0,1.0,2.0,38.0,12.0,0.0,NaN,0.0,5.0,4.0,15.0,257.0

In [62]:
hora11+hora12+hora13

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,0.0,86.0,37.0,0.0,107.0,15.0,31.0,22.0,75.0,8.0,30.0,18.0,88.0,19.0,41.0,8.0,1.0
5,2.0,41.0,1.0,0.0,3.0,0.0,4.0,5.0,1.0,1.0,0.0,31.0,6.0,37.0,119.0,0.0,3.0
7,7.0,24.0,0.0,0.0,34.0,2.0,37.0,3.0,10.0,2.0,1.0,4.0,2.0,47.0,2.0,12.0,6.0
8,36.0,1.0,0.0,1.0,6.0,0.0,2.0,8.0,5.0,1.0,10.0,0.0,6.0,2.0,4.0,0.0,3.0
10,59.0,46.0,25.0,27.0,8.0,109.0,17.0,8.0,249.0,20.0,6.0,7.0,27.0,28.0,8.0,199.0,138.0
13,24.0,8.0,1.0,10.0,84.0,7.0,3.0,4.0,56.0,1.0,0.0,0.0,1.0,4.0,0.0,41.0,67.0
14,3.0,15.0,15.0,0.0,6.0,3.0,2.0,4.0,3.0,3.0,3.0,6.0,5.0,41.0,12.0,4.0,16.0
15,14.0,8.0,20.0,0.0,9.0,5.0,11.0,1.0,11.0,1.0,2.0,1.0,6.0,9.0,2.0,0.0,4.0
17,29.0,26.0,6.0,7.0,272.0,71.0,3.0,2.0,47.0,12.0,3.0,2.0,18.0,22.0,2.0,88.0,141.0
18,0.0,1.0,0.0,0.0,9.0,1.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,5.0
20,33.0,7.0,6.0,0.0,14.0,0.0,4.0,4.0,15.0,2.0,0.0,4.0,30.0,1.0,5.0,3.0,0.0
21,1.0,381.0,0.0,0.0,0.0,0.0,3.0,2.0,0.0,0.0,0.0,24.0,1.0,1.0,0.0,0.0,0.0
23,45.0,33.0,6.0,0.0,8.0,0.0,7.0,7.0,6.0,1.0,8.0,0.0,5.0,8.0,10.0,1.0,0.0
28,4.0,5.0,0.0,0.0,2.0,0.0,0.0,3.0,1.0,1.0,5.0,2.0,0.0,0.0,9.0,0.0,4.0
30,0.0,0.0,0.0,0.0,2.0,1.0,2.0,0.0,1.0,3.0,0.0,0.0,0.0,3.0,8.0,0.0,5.0
32,45.0,7.0,28.0,24.0,13.0,3.0,5.0,5.0,13.0,2.0,4.0,4.0,7.0,5.0,3.0,20.0,14.0
33,3.0,4.0,5.0,3.0,75.0,95.0,19.0,3.0,76.0,27.0,0.0,0.0,0.0,7.0,6.0,19.0,416.0

In [63]:
hora12+hora13+hora14

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,0.0,24.0,19.0,0.0,37.0,11.0,9.0,11.0,57.0,8.0,31.0,2.0,73.0,15.0,24.0,6.0,1.0
5,2.0,39.0,1.0,0.0,3.0,0.0,4.0,4.0,3.0,1.0,1.0,20.0,4.0,16.0,136.0,0.0,4.0
7,6.0,25.0,0.0,0.0,29.0,1.0,25.0,3.0,6.0,3.0,0.0,1.0,2.0,44.0,1.0,8.0,5.0
8,35.0,1.0,1.0,0.0,6.0,1.0,2.0,8.0,5.0,1.0,11.0,0.0,5.0,2.0,4.0,0.0,2.0
10,55.0,45.0,24.0,25.0,13.0,133.0,17.0,6.0,286.0,24.0,5.0,6.0,28.0,19.0,4.0,175.0,131.0
13,13.0,2.0,0.0,11.0,71.0,7.0,5.0,2.0,41.0,1.0,0.0,0.0,0.0,2.0,1.0,27.0,64.0
14,5.0,19.0,14.0,0.0,6.0,4.0,3.0,4.0,4.0,4.0,1.0,6.0,5.0,51.0,9.0,1.0,14.0
15,5.0,4.0,15.0,0.0,8.0,5.0,17.0,1.0,4.0,2.0,1.0,1.0,3.0,9.0,2.0,0.0,2.0
17,28.0,20.0,5.0,8.0,257.0,77.0,1.0,2.0,44.0,13.0,3.0,0.0,16.0,17.0,2.0,81.0,122.0
18,0.0,0.0,0.0,0.0,4.0,2.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
20,30.0,2.0,4.0,0.0,2.0,0.0,2.0,0.0,4.0,1.0,0.0,3.0,26.0,0.0,2.0,3.0,0.0
21,0.0,392.0,0.0,0.0,0.0,0.0,3.0,2.0,0.0,0.0,0.0,35.0,1.0,2.0,0.0,0.0,0.0
23,27.0,25.0,6.0,0.0,7.0,0.0,6.0,6.0,2.0,2.0,5.0,0.0,7.0,7.0,14.0,1.0,0.0
28,3.0,8.0,0.0,0.0,2.0,1.0,0.0,6.0,2.0,4.0,5.0,2.0,2.0,0.0,18.0,0.0,4.0
30,0.0,1.0,0.0,0.0,2.0,1.0,2.0,0.0,2.0,3.0,0.0,0.0,0.0,2.0,9.0,0.0,5.0
32,43.0,6.0,32.0,23.0,15.0,5.0,5.0,3.0,9.0,2.0,3.0,3.0,7.0,7.0,3.0,19.0,8.0
33,2.0,4.0,5.0,4.0,76.0,89.0,19.0,3.0,78.0,24.0,0.0,0.0,0.0,12.0,6.0,11.0,368.0

In [64]:
hora13+hora14+hora15

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,0.0,11.0,14.0,0.0,31.0,9.0,8.0,10.0,45.0,1.0,27.0,1.0,60.0,12.0,3.0,8.0,0.0
5,1.0,46.0,1.0,0.0,18.0,0.0,7.0,4.0,5.0,6.0,2.0,26.0,5.0,57.0,132.0,0.0,3.0
7,3.0,16.0,0.0,0.0,26.0,1.0,15.0,1.0,8.0,2.0,0.0,2.0,1.0,40.0,1.0,5.0,2.0
8,27.0,0.0,4.0,2.0,5.0,3.0,2.0,2.0,8.0,1.0,6.0,0.0,6.0,1.0,1.0,0.0,10.0
10,23.0,14.0,17.0,17.0,17.0,112.0,8.0,3.0,215.0,41.0,6.0,3.0,17.0,40.0,3.0,149.0,104.0
13,7.0,4.0,0.0,7.0,43.0,9.0,3.0,3.0,36.0,1.0,0.0,0.0,0.0,1.0,1.0,11.0,74.0
14,8.0,11.0,9.0,0.0,4.0,1.0,3.0,7.0,3.0,2.0,1.0,1.0,5.0,61.0,6.0,0.0,0.0
15,3.0,8.0,14.0,0.0,18.0,11.0,16.0,1.0,8.0,2.0,2.0,0.0,3.0,45.0,6.0,0.0,2.0
17,24.0,14.0,2.0,12.0,205.0,76.0,1.0,1.0,44.0,14.0,4.0,1.0,16.0,10.0,3.0,55.0,102.0
18,0.0,0.0,0.0,0.0,8.0,2.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
20,38.0,1.0,2.0,0.0,6.0,0.0,1.0,2.0,6.0,1.0,0.0,2.0,25.0,0.0,1.0,2.0,0.0
21,2.0,411.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,0.0,45.0,1.0,3.0,0.0,0.0,0.0
23,41.0,34.0,8.0,0.0,4.0,0.0,4.0,3.0,6.0,3.0,6.0,0.0,8.0,8.0,9.0,1.0,0.0
28,2.0,9.0,0.0,0.0,9.0,1.0,0.0,3.0,1.0,5.0,4.0,1.0,4.0,1.0,24.0,0.0,6.0
30,0.0,1.0,0.0,0.0,25.0,1.0,2.0,0.0,2.0,8.0,0.0,1.0,0.0,16.0,18.0,0.0,4.0
32,34.0,7.0,26.0,18.0,9.0,4.0,5.0,1.0,4.0,1.0,1.0,2.0,10.0,8.0,1.0,11.0,13.0
33,1.0,4.0,5.0,3.0,45.0,69.0,21.0,4.0,77.0,21.0,0.0,0.0,0.0,12.0,5.0,8.0,426.0

In [65]:
hora14+hora15+hora16

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,0.0,12.0,18.0,0.0,39.0,8.0,7.0,12.0,51.0,3.0,41.0,2.0,56.0,10.0,1.0,8.0,0.0
5,1.0,38.0,1.0,0.0,22.0,0.0,6.0,3.0,5.0,6.0,2.0,25.0,3.0,53.0,119.0,0.0,4.0
7,4.0,16.0,2.0,0.0,25.0,4.0,19.0,0.0,10.0,1.0,0.0,4.0,2.0,28.0,1.0,7.0,3.0
8,24.0,0.0,4.0,5.0,1.0,4.0,2.0,2.0,8.0,1.0,2.0,0.0,3.0,1.0,0.0,0.0,9.0
10,15.0,11.0,15.0,6.0,15.0,91.0,6.0,5.0,183.0,31.0,4.0,2.0,12.0,36.0,1.0,123.0,69.0
13,9.0,4.0,1.0,6.0,64.0,6.0,3.0,1.0,34.0,1.0,0.0,0.0,0.0,1.0,1.0,19.0,61.0
14,5.0,12.0,13.0,0.0,5.0,3.0,2.0,6.0,2.0,2.0,0.0,4.0,3.0,60.0,5.0,1.0,9.0
15,3.0,9.0,12.0,0.0,21.0,12.0,19.0,1.0,7.0,2.0,2.0,0.0,1.0,45.0,6.0,1.0,3.0
17,15.0,14.0,2.0,11.0,173.0,60.0,2.0,2.0,43.0,3.0,3.0,1.0,9.0,12.0,2.0,47.0,106.0
18,0.0,0.0,0.0,0.0,10.0,1.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0
20,33.0,2.0,4.0,0.0,5.0,0.0,2.0,4.0,5.0,0.0,0.0,3.0,22.0,0.0,1.0,0.0,0.0
21,5.0,317.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,43.0,0.0,3.0,0.0,0.0,0.0
23,35.0,36.0,7.0,0.0,8.0,0.0,2.0,3.0,14.0,3.0,11.0,1.0,6.0,7.0,6.0,2.0,0.0
28,1.0,8.0,0.0,0.0,30.0,1.0,0.0,6.0,1.0,8.0,0.0,4.0,4.0,1.0,25.0,0.0,8.0
30,0.0,1.0,0.0,0.0,32.0,1.0,1.0,0.0,2.0,10.0,0.0,1.0,0.0,16.0,22.0,0.0,4.0
32,20.0,5.0,23.0,18.0,4.0,2.0,5.0,1.0,6.0,1.0,1.0,0.0,10.0,6.0,2.0,7.0,10.0
33,1.0,4.0,3.0,3.0,44.0,42.0,3.0,3.0,44.0,7.0,0.0,0.0,0.0,19.0,12.0,9.0,323.0

In [66]:
hora15+hora16+hora17

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,0.0,8.0,20.0,0.0,40.0,5.0,11.0,21.0,40.0,2.0,44.0,2.0,46.0,15.0,1.0,10.0,0.0
5,3.0,30.0,1.0,0.0,23.0,0.0,5.0,8.0,3.0,6.0,3.0,37.0,4.0,51.0,89.0,0.0,3.0
7,13.0,7.0,3.0,0.0,19.0,8.0,29.0,1.0,17.0,1.0,2.0,5.0,3.0,26.0,1.0,13.0,8.0
8,20.0,0.0,3.0,6.0,0.0,3.0,1.0,1.0,7.0,1.0,1.0,0.0,2.0,1.0,0.0,0.0,10.0
10,12.0,5.0,13.0,7.0,16.0,81.0,3.0,4.0,139.0,27.0,6.0,3.0,7.0,31.0,2.0,147.0,84.0
13,13.0,2.0,1.0,2.0,67.0,6.0,1.0,2.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,50.0
14,5.0,8.0,16.0,0.0,6.0,3.0,0.0,10.0,2.0,1.0,0.0,4.0,2.0,46.0,3.0,4.0,10.0
15,6.0,12.0,14.0,0.0,20.0,12.0,13.0,1.0,16.0,1.0,2.0,1.0,2.0,43.0,5.0,2.0,5.0
17,15.0,3.0,0.0,10.0,158.0,60.0,2.0,2.0,38.0,4.0,5.0,2.0,7.0,5.0,1.0,40.0,104.0
18,0.0,0.0,0.0,0.0,16.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,10.0
20,33.0,4.0,5.0,0.0,7.0,0.0,2.0,5.0,5.0,0.0,0.0,1.0,18.0,0.0,0.0,0.0,0.0
21,7.0,323.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,43.0,0.0,1.0,0.0,0.0,0.0
23,40.0,31.0,7.0,0.0,7.0,0.0,2.0,4.0,14.0,1.0,11.0,2.0,6.0,5.0,0.0,2.0,0.0
28,2.0,5.0,0.0,0.0,34.0,0.0,1.0,3.0,0.0,6.0,0.0,4.0,2.0,1.0,18.0,0.0,6.0
30,0.0,0.0,1.0,0.0,31.0,0.0,1.0,0.0,1.0,12.0,0.0,1.0,0.0,17.0,24.0,0.0,3.0
32,14.0,8.0,14.0,18.0,4.0,0.0,5.0,2.0,5.0,1.0,1.0,2.0,8.0,3.0,1.0,5.0,8.0
33,3.0,5.0,3.0,3.0,46.0,43.0,2.0,3.0,54.0,11.0,0.0,0.0,0.0,13.0,10.0,15.0,304.0

In [67]:
hora16+hora17+hora18

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,0.0,6.0,20.0,NaN,36.0,4.0,11.0,24.0,37.0,NaN,48.0,NaN,41.0,15.0,NaN,13.0,0.0
5,4.0,18.0,0.0,NaN,7.0,0.0,4.0,12.0,0.0,NaN,3.0,NaN,4.0,15.0,NaN,0.0,1.0
7,16.0,12.0,4.0,NaN,16.0,8.0,33.0,3.0,13.0,NaN,2.0,NaN,3.0,34.0,NaN,16.0,8.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,15.0,8.0,12.0,NaN,10.0,79.0,5.0,3.0,117.0,NaN,3.0,NaN,5.0,17.0,NaN,114.0,74.0
13,11.0,1.0,1.0,NaN,59.0,3.0,2.0,1.0,25.0,NaN,0.0,NaN,0.0,1.0,NaN,17.0,21.0
14,4.0,6.0,19.0,NaN,5.0,3.0,2.0,9.0,1.0,NaN,0.0,NaN,2.0,25.0,NaN,4.0,10.0
15,8.0,5.0,10.0,NaN,6.0,6.0,9.0,1.0,12.0,NaN,1.0,NaN,2.0,7.0,NaN,2.0,3.0
17,8.0,3.0,0.0,NaN,139.0,41.0,2.0,3.0,25.0,NaN,3.0,NaN,5.0,12.0,NaN,34.0,79.0
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,36.0,4.0,3.0,NaN,5.0,0.0,2.0,4.0,2.0,NaN,0.0,NaN,16.0,1.0,NaN,0.0,0.0
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,36.0,14.0,5.0,NaN,6.0,0.0,2.0,4.0,10.0,NaN,11.0,NaN,5.0,1.0,NaN,2.0,0.0
28,3.0,3.0,0.0,NaN,27.0,0.0,2.0,5.0,0.0,NaN,0.0,NaN,1.0,0.0,NaN,0.0,3.0
30,0.0,0.0,1.0,NaN,8.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,1.0,1.0,NaN,0.0,2.0
32,11.0,6.0,12.0,NaN,2.0,0.0,5.0,2.0,4.0,NaN,1.0,NaN,2.0,6.0,NaN,4.0,0.0
33,2.0,3.0,4.0,NaN,43.0,36.0,1.0,0.0,44.0,NaN,0.0,NaN,0.0,11.0,NaN,14.0,153.0

In [68]:
hora17+hora18+hora19

NEW_PontoFinal,1,5,7,8,10,13,14,15,17,18,20,21,23,28,30,32,33
NEW_PontoInicial,,,,,,,,,,,,,,,,,
1,0.0,2.0,16.0,NaN,26.0,3.0,10.0,21.0,22.0,NaN,30.0,NaN,23.0,13.0,NaN,11.0,0.0
5,4.0,9.0,0.0,NaN,1.0,0.0,4.0,12.0,0.0,NaN,3.0,NaN,4.0,13.0,NaN,0.0,0.0
7,16.0,9.0,2.0,NaN,16.0,5.0,25.0,4.0,15.0,NaN,2.0,NaN,2.0,33.0,NaN,14.0,5.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,16.0,7.0,13.0,NaN,7.0,70.0,5.0,0.0,88.0,NaN,2.0,NaN,4.0,20.0,NaN,108.0,65.0
13,7.0,1.0,0.0,NaN,24.0,2.0,1.0,1.0,14.0,NaN,0.0,NaN,0.0,1.0,NaN,6.0,9.0
14,5.0,2.0,17.0,NaN,3.0,1.0,2.0,8.0,4.0,NaN,1.0,NaN,2.0,21.0,NaN,3.0,1.0
15,8.0,5.0,4.0,NaN,2.0,2.0,5.0,2.0,9.0,NaN,0.0,NaN,2.0,5.0,NaN,1.0,2.0
17,6.0,1.0,3.0,NaN,112.0,38.0,0.0,2.0,20.0,NaN,2.0,NaN,4.0,9.0,NaN,29.0,46.0
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,31.0,3.0,1.0,NaN,7.0,0.0,1.0,5.0,1.0,NaN,0.0,NaN,8.0,1.0,NaN,1.0,0.0
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,36.0,7.0,7.0,NaN,2.0,0.0,3.0,4.0,2.0,NaN,5.0,NaN,5.0,0.0,NaN,1.0,0.0
28,2.0,2.0,0.0,NaN,6.0,0.0,2.0,3.0,0.0,NaN,1.0,NaN,2.0,0.0,NaN,0.0,1.0
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,6.0,5.0,12.0,NaN,2.0,0.0,4.0,1.0,2.0,NaN,1.0,NaN,2.0,5.0,NaN,2.0,0.0
33,2.0,1.0,2.0,NaN,25.0,25.0,1.0,0.0,35.0,NaN,0.0,NaN,0.0,2.0,NaN,9.0,80.0

In [69]:
hora678     = hora6 +hora7 +hora8
hora789     = hora7 +hora8 +hora9
hora8910    = hora8 +hora9+hora10
hora91011   = hora9+hora10+hora11
hora101112  = hora10+hora11+hora12
hora111213  = hora11+hora12+hora13
hora121314  = hora12+hora13+hora14
hora131415  = hora13+hora14+hora15
hora141516  = hora14+hora15+hora16
hora151617  = hora15+hora16+hora17
hora161718  = hora16+hora17+hora18
hora171819  = hora17+hora18+hora19

In [71]:
# writer = pd.ExcelWriter('../Output de dados/OD_horarias acumulada.xlsx', engine='xlsxwriter')

# # Write each dataframe to a different worksheet.
# hora678     .to_excel(writer, sheet_name='hora678')
# hora789     .to_excel(writer, sheet_name='hora789')
# hora8910    .to_excel(writer, sheet_name='hora8910')
# hora91011   .to_excel(writer, sheet_name='hora91011')
# hora101112  .to_excel(writer, sheet_name='hora101112')
# hora111213  .to_excel(writer, sheet_name='hora111213')
# hora121314  .to_excel(writer, sheet_name='hora121314')
# hora131415  .to_excel(writer, sheet_name='hora131415')
# hora141516  .to_excel(writer, sheet_name='hora141516')
# hora151617  .to_excel(writer, sheet_name='hora151617')
# hora161718  .to_excel(writer, sheet_name='hora161718')
# hora171819  .to_excel(writer, sheet_name='hora171819')

# # # Close the Pandas Excel writer and output the Excel file.
# writer.save()